replicaCount: 1
image:
  repository: nginx
  tag: "1.24"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: dev.sonth-my-app.com
  tls:
    - secretName: dev-tls
      hosts:
        - dev.sonth-my-app.com
